# Subnets where instance will be hosted
Parameters:
  myVPC:
    Description: Select One VPC available in your existing account
    Type: AWS::EC2::VPC::Id
    Default: "<Your VPC ID>"
Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'us-west-2b'
      MapPublicIpOnLaunch: true
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'us-west-2b'
      MapPublicIpOnLaunch: false
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet

Outputs:
  outputPublicSubnet:
    Description: A reference to the created PublicSubnet
    Value: !Ref PublicSubnet

  outputPrivateSubnet:
    Description: A reference to the created PrivateSubnet
    Value: !Ref PrivateSubnet
